#!/bin/bash

HELPDOC=$(
    cat <<EOF
Usage: goto [ui|(actions|repo)|gh]


EOF
)

if [ $# -eq 0 ]; then
    echo $HELPDOC
    open "https://github.com/connoro7/Adv360-Pro-ZMK/actions"
    exit 0
fi

ACTION=$1

case $ACTION in
"ui")
    open "https://kinesiscorporation.github.io/Adv360-Pro-GUI/"
    ;;
"actions" | "repo" | "r")
    open "https://github.com/connoro7/Adv360-Pro-ZMK/actions"
    ;;
"gh")
    open "https://github.com/connoro7/Adv360-Pro-ZMK"
    ;;
*)
    echo $HELPDOC
    ;;
esac
