#!/bin/bash

# Flashes firmware onto board

OS=$(uname)

if [ "$OS" = "Darwin" ]; then
    cp ./firmware/*-left.uf2 /Volumes/ADV360PRO
elif [ "$OS" = "Linux" ]; then
    cp ./firmware/*-left.uf2 /media/$USER/ADV360PRO
else
    echo "Unsupported operating system: $OS"
fi

